language: php

matrix:
  fast_finish: true
  include:
    - php: "7.4"
#    - php: "7.3"
#    - php: "7.2"
    - php: "7.1"
#    - php: "7.0"
#    - php: "5.6"
#    - php: "5.5"
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-source --dev --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  travis_retry composer install --no-interaction --prefer-dist


script: ./vendor/bin/phpunit --coverage-text
