language: php
git:
  clone: false
matrix:
  fast_finish: true
  include:
    - php: "7.4"
    - php: "7.3"
    - php: "7.2"
    - php: "7.1"
    - php: "7.0"
    - php: "5.6"
    - php: "5.5"
      dist: trusty
    - php: "5.4"
      dist: trusty
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
    - TASK_TESTS_COVERAGE=0

# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache

install:
  - travis_retry composer self-update
  - travis_retry composer require wxxiong6/tree
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS

script: phpunit --bootstrap vendor/autoload.php --no-configuration --filter "/(::testMakeTree)( .*)?$/" TreeTest vendor/tests/TreeTest.php