language: php
matrix:
  fast_finish: true
  include:
    - php: "7.4"
    - php: "7.3"
    - php: "7.2"
    - php: "7.1"
      env:
        - TASK_TESTS_COVERAGE=1
    - php: "7.0"
    - php: "5.6"
    - php: "5.5"
      dist: trusty
    - php: "5.4"
      dist: trusty
env:
  global:
    - DEFAULT_COMPOSER_FLAGS="--prefer-dist --no-interaction --no-progress --optimize-autoloader"
    - TASK_TESTS_PHP=1
# cache vendor dirs
cache:
  directories:
    - vendor
    - $HOME/.composer/cache
bofore_script:
  - composer install
  - cd tests
install:
  # install composer dependencies
  - travis_retry composer self-update
  - export PATH="$HOME/.composer/vendor/bin:$PATH"
  - travis_retry composer update $DEFAULT_COMPOSER_FLAGS


script: phpunit --no-configuration --filter "/(::testMakeTree)( .*)?$/" TreeTest tests/TreeTest.php